[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]
orm_desafio_v1 = { path = "./orm_desafio_v1"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.115"
rocket = { version = "0.5.0", features = ["json"] }